# Numpy

In [1]:
import numpy as np

# DataTypes & Attributes

In [2]:
## Numpy main datatype is ndarray
a1 = np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [234]:
a2 = np.array([[1,2,3.4],
              [4,7.4,7]])

In [6]:
a3 = np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
              [[10,11,13],
               [14,15,16],
               [17,18,19]]])

In [7]:
a2

array([[1. , 2. , 3.4],
       [4. , 7.4, 7. ]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [9]:
type(a2)

numpy.ndarray

In [10]:
type(a3)

numpy.ndarray

In [11]:
# shape
a1.shape

(3,)

In [12]:
a2.shape

(2, 3)

In [13]:
a3.shape

(2, 3, 3)

In [14]:
# dimantion
a1.ndim

1

In [15]:
a2.ndim

2

In [16]:
a3.ndim

3

In [17]:
# data type of elements of number
a1.dtype

dtype('int32')

In [18]:
a2.dtype # if one or more than one elemnts are float than all array are float

dtype('float64')

In [19]:
a3.dtype

dtype('int32')

In [20]:
# size - return number of elements in array
a1.size

3

In [21]:
a2.size

6

In [22]:
a3.size

18

In [23]:
# create dataframe from a numpy array
import pandas as pd

In [24]:
df = pd.DataFrame(a2)

In [25]:
a2

array([[1. , 2. , 3.4],
       [4. , 7.4, 7. ]])

In [26]:
df

0    1    2
0  1.0  2.0  3.4
1  4.0  7.4  7.0

In [27]:
# create serias from a numpy array
se = pd.Series(a1)

In [28]:
se

0    1
1    2
2    3
dtype: int32

In [29]:
df1 = pd.DataFrame(a1)

In [30]:
df1

0
0  1
1  2
2  3

In [31]:
df

0    1    2
0  1.0  2.0  3.4
1  4.0  7.4  7.0

In [32]:
a4 = np.array([2,2.0,"2",'2'])

In [33]:
a4

array(['2', '2.0', '2', '2'], dtype='<U32')

In [34]:
a4.dtype # all the convert string data type

dtype('<U32')

In [35]:
a5 = np.array([[1,2,3],
              [1,2,""]])

# Creating arrays

In [36]:
sample_array = np.array([1,2,3])

In [37]:
sample_array

array([1, 2, 3])

In [38]:
sample_array.dtype

dtype('int32')

In [39]:
ones = np.ones((2,3))

In [40]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [41]:
ones.dtype

dtype('float64')

In [42]:
type(ones)

numpy.ndarray

In [43]:
zeros = np.zeros((2,3,2,4))

In [44]:
zeros

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [45]:
zeros.ndim

4

In [46]:
ones.ndim

2

In [47]:
zeros.dtype

dtype('float64')

In [48]:
range_array = np.arange(0,20,3)

In [49]:
range_array

array([ 0,  3,  6,  9, 12, 15, 18])

In [50]:
range_array.size

7

In [51]:
range_array.ndim

1

In [52]:
range_array.dtype

dtype('int32')

In [53]:
range_array.shape

(7,)

In [54]:
rondam_array = np.random.randint(0,10,size=(3,5))

In [55]:
rondam_array

array([[4, 5, 6, 8, 5],
       [5, 8, 1, 0, 6],
       [0, 9, 5, 5, 6]])

In [56]:
rondam_array2 = np.random.random((5,3))

In [57]:
rondam_array2

array([[0.78658029, 0.68434047, 0.93578727],
       [0.85683611, 0.92516345, 0.28547091],
       [0.5030336 , 0.76496955, 0.59012205],
       [0.32002963, 0.17508381, 0.4400391 ],
       [0.94048691, 0.43072482, 0.02274098]])

In [58]:
rondam_array3 = np.random.rand(5,3)
# check diffrence between random.random & random.rand

In [59]:
rondam_array3

array([[0.1267312 , 0.79210982, 0.80912391],
       [0.13243677, 0.69426172, 0.14421369],
       [0.53682709, 0.92619572, 0.11851756],
       [0.1181856 , 0.43073789, 0.90071202],
       [0.50563571, 0.9849829 , 0.26850532]])

In [60]:
rondam_array4 = np.random.rand(2,2,3)

In [61]:
rondam_array4

array([[[5.20349589e-01, 9.46887894e-01, 4.98774059e-01],
        [8.27006006e-01, 1.09435789e-01, 9.12049151e-01]],

       [[9.14351775e-02, 4.60639403e-01, 3.33884373e-04],
        [6.86115259e-01, 9.32587597e-01, 3.53587924e-01]]])

In [62]:
rondam_array4.shape

(2, 2, 3)

In [63]:
rondam_array4.ndim

3

In [64]:
rondam_array4.dtype

dtype('float64')

In [65]:
rondam_array4.size

12

In [66]:
random_array5 = np.random.randint(0,10,size=(4,3))

In [67]:
random_array5

array([[7, 2, 9],
       [5, 3, 9],
       [9, 0, 7],
       [9, 6, 5]])

In [68]:
# seed - pseudo-random numbers - it is one time create array than not change
# it's define in cell and it's sckop within cell
np.random.seed(1)
random_array6 = np.random.randint(0,10,size=(4,3))
random_array6 

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4]])

In [69]:
#np.random.seed(seed=0)
random_array7 = np.random.randint(0,10,size=(4,3))
random_array7 

array([[5, 2, 4],
       [2, 4, 7],
       [7, 9, 1],
       [7, 0, 6]])

# Viewing arrays and Matrices

In [70]:
np.unique(random_array7)

array([0, 1, 2, 4, 5, 6, 7, 9])

In [71]:
a1

array([1, 2, 3])

In [72]:
a2

array([[1. , 2. , 3.4],
       [4. , 7.4, 7. ]])

In [73]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [74]:
a1[0]

1

In [75]:
a1[0]

1

In [76]:
a2[0]

array([1. , 2. , 3.4])

In [77]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [78]:
a3[0][0][0]

1

In [79]:
a3[0][1][1]

5

In [80]:
a3[0][2][1]

8

In [81]:
a3[0][2]

array([7, 8, 9])

In [82]:
a3[:2, :2, :2] #sliceing

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [14, 15]]])

In [86]:
a3[0:2, 0:2, 0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [14, 15]]])

In [84]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [87]:
a3[0:3,0:3,0:3]

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [88]:
a4 = np.random.randint(10,size=(2,3,4,5))

In [89]:
a4

array([[[[9, 9, 7, 6, 9],
         [1, 0, 1, 8, 8],
         [3, 9, 8, 7, 3],
         [6, 5, 1, 9, 3]],

        [[4, 8, 1, 4, 0],
         [3, 9, 2, 0, 4],
         [9, 2, 7, 7, 9],
         [8, 6, 9, 3, 7]],

        [[7, 4, 5, 9, 3],
         [6, 8, 0, 2, 7],
         [7, 9, 7, 3, 0],
         [8, 7, 7, 1, 1]]],


       [[[3, 0, 8, 6, 4],
         [5, 6, 2, 5, 7],
         [8, 4, 4, 7, 7],
         [4, 9, 0, 2, 0]],

        [[7, 1, 7, 9, 8],
         [4, 0, 1, 9, 8],
         [2, 3, 1, 2, 7],
         [2, 6, 0, 9, 2]],

        [[6, 6, 2, 7, 7],
         [0, 6, 5, 1, 4],
         [6, 0, 6, 5, 1],
         [2, 1, 5, 4, 0]]]])

In [92]:
a4[:1,:2,:3,:4]

array([[[[9, 9, 7, 6],
         [1, 0, 1, 8],
         [3, 9, 8, 7]],

        [[4, 8, 1, 4],
         [3, 9, 2, 0],
         [9, 2, 7, 7]]]])

In [93]:
a4[:1,:1,:1,:5]

array([[[[9, 9, 7, 6, 9]]]])

In [96]:
a4[:,:,:,:3]

array([[[[9, 9, 7],
         [1, 0, 1],
         [3, 9, 8],
         [6, 5, 1]],

        [[4, 8, 1],
         [3, 9, 2],
         [9, 2, 7],
         [8, 6, 9]],

        [[7, 4, 5],
         [6, 8, 0],
         [7, 9, 7],
         [8, 7, 7]]],


       [[[3, 0, 8],
         [5, 6, 2],
         [8, 4, 4],
         [4, 9, 0]],

        [[7, 1, 7],
         [4, 0, 1],
         [2, 3, 1],
         [2, 6, 0]],

        [[6, 6, 2],
         [0, 6, 5],
         [6, 0, 6],
         [2, 1, 5]]]])

# Manipulating & Comparing arrays

# Arithmetic

In [97]:
a1

array([1, 2, 3])

In [98]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [99]:
a1+ones

array([[2., 3., 4.],
       [2., 3., 4.]])

In [102]:
a5 = np.array([2,2,2])

In [103]:
a5+ones

array([[3., 3., 3.],
       [3., 3., 3.]])

In [104]:
ones1 = np.ones(3)

In [105]:
a1

array([1, 2, 3])

In [106]:
a1+ones1

array([2., 3., 4.])

In [107]:
a1-ones

array([[0., 1., 2.],
       [0., 1., 2.]])

In [108]:
a5-ones1

array([1., 1., 1.])

In [109]:
a1*ones

array([[1., 2., 3.],
       [1., 2., 3.]])

In [110]:
a5*ones

array([[2., 2., 2.],
       [2., 2., 2.]])

In [111]:
a5*ones1

array([2., 2., 2.])

In [112]:
a1*ones1

array([1., 2., 3.])

In [113]:
a1

array([1, 2, 3])

In [114]:
a2

array([[1. , 2. , 3.4],
       [4. , 7.4, 7. ]])

In [115]:
a1*a2

array([[ 1. ,  4. , 10.2],
       [ 4. , 14.8, 21. ]])

In [116]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [118]:
a6 = np.random.randint(10,size=(3,3))

In [119]:
a6

array([[7, 8, 9],
       [5, 7, 0],
       [9, 3, 9]])

In [120]:
# smaller array shape match with larger array ending shape
a3*a6
# here a6 is smaller shape - (3,3)
# here a3 is larger  shape - (2,3,3)
# here (x,3,3) = (3,3) that way it is possible
# or vise varsa like - if any array a0 shape - (2,3,1)
# then a3 * a0 is possible 
# here (2,3,1) = (2,3,x) 

array([[[  7,  16,  27],
        [ 20,  35,   0],
        [ 63,  24,  81]],

       [[ 70,  88, 117],
        [ 70, 105,   0],
        [153,  54, 171]]])

In [177]:
a0 = np.array([[[6],[6],[6]],
               [[6],[6],[6]]])

In [178]:
a0.shape

(2, 3, 1)

In [122]:
a6/a3

array([[[7.        , 4.        , 3.        ],
        [1.25      , 1.4       , 0.        ],
        [1.28571429, 0.375     , 1.        ]],

       [[0.7       , 0.72727273, 0.69230769],
        [0.35714286, 0.46666667, 0.        ],
        [0.52941176, 0.16666667, 0.47368421]]])

In [179]:
a0*a3

array([[[  6,  12,  18],
        [ 24,  30,  36],
        [ 42,  48,  54]],

       [[ 60,  66,  78],
        [ 84,  90,  96],
        [102, 108, 114]]])

In [123]:
a2 * a3
# not possible beacuse a2 shape - (2,3)
#                      a3 shape - (2,3,3)
#                here  (x,3,3) != (2,3) that way it's not possible

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [124]:
a1*a3

array([[[ 1,  4,  9],
        [ 4, 10, 18],
        [ 7, 16, 27]],

       [[10, 22, 39],
        [14, 30, 48],
        [17, 36, 57]]])

In [125]:
a7 = np.array([[1],[2]])

In [126]:
a2

array([[1. , 2. , 3.4],
       [4. , 7.4, 7. ]])

In [127]:
a2*a7

array([[ 1. ,  2. ,  3.4],
       [ 8. , 14.8, 14. ]])

In [128]:
a2.shape

(2, 3)

In [129]:
a2*a3
# how to reshape a2 for multiple with a3 ?

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [130]:
a2/a1


array([[1.        , 1.        , 1.13333333],
       [4.        , 3.7       , 2.33333333]])

In [131]:
a2//a1 # remove decimal

array([[1., 1., 1.],
       [4., 3., 2.]])

In [132]:
a2 **2 # power of 2 given elements

array([[ 1.  ,  4.  , 11.56],
       [16.  , 54.76, 49.  ]])

In [133]:
a3 ** 3 # power 3

array([[[   1,    8,   27],
        [  64,  125,  216],
        [ 343,  512,  729]],

       [[1000, 1331, 2197],
        [2744, 3375, 4096],
        [4913, 5832, 6859]]], dtype=int32)

In [135]:
np.square(a2)

array([[ 1.  ,  4.  , 11.56],
       [16.  , 54.76, 49.  ]])

In [136]:
np.add(a1,ones)

array([[2., 3., 4.],
       [2., 3., 4.]])

In [137]:
a2 % 2

array([[1. , 0. , 1.4],
       [0. , 1.4, 1. ]])

In [138]:
a1 % 2

array([1, 0, 1], dtype=int32)

In [139]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [140]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

# Aggregation

In [141]:
# aggregation - performing the same operation on a number of things

In [142]:
list1 = [1,2,3]

In [143]:
type(list1)

list

In [144]:
sum(list1)

6

In [146]:
a1

array([1, 2, 3])

In [147]:
sum(a1)
# python methods - python datatype

6

In [148]:
np.sum(a1)
# numpy methods - numpy datatype

6

In [149]:
# create one massive array
massive_array = np.random.random(100000)

In [151]:
massive_array.size

100000

In [156]:
massive_array[:10]

array([0.74276483, 0.19195608, 0.4643115 , 0.23036281, 0.50824754,
       0.20856831, 0.04930424, 0.51886188, 0.17227835, 0.39631329])

In [157]:
%timeit sum(massive_array) # python sum()

8.98 ms ± 176 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [158]:
%timeit np.sum(massive_array) # numpy np.sum()

45.5 µs ± 996 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [159]:
# here ( 8.98 ms >>> 45.5 us ) numpy is more more faster

In [160]:
np.mean(a2)

4.133333333333334

In [161]:
np.max(a2)

7.4

In [162]:
np.min(a2)

1.0

In [163]:
np.std(a2)

2.3739325086353142

In [164]:
np.var(a2)

5.635555555555555

In [165]:
2.3739325086353142 * 2.3739325086353142

5.635555555555556

# Reshaping & Transposing

In [166]:
a2

array([[1. , 2. , 3.4],
       [4. , 7.4, 7. ]])

In [167]:
a2.shape

(2, 3)

In [168]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [169]:
a3.shape

(2, 3, 3)

In [170]:
a2*a3 # this is the problem

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [171]:
# Reshape
a2.reshape(2,3,1)

array([[[1. ],
        [2. ],
        [3.4]],

       [[4. ],
        [7.4],
        [7. ]]])

In [172]:
a2.shape

(2, 3)

In [173]:
a2_reshape = a2.reshape(2,3,1)

In [174]:
a2_reshape * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.8,  27.2,  30.6]],

       [[ 40. ,  44. ,  52. ],
        [103.6, 111. , 118.4],
        [119. , 126. , 133. ]]])

In [175]:
a2_reshape

array([[[1. ],
        [2. ],
        [3.4]],

       [[4. ],
        [7.4],
        [7. ]]])

In [176]:
a2_reshape.shape

(2, 3, 1)

In [182]:
a2_reshape*a1

array([[[ 1. ,  2. ,  3. ],
        [ 2. ,  4. ,  6. ],
        [ 3.4,  6.8, 10.2]],

       [[ 4. ,  8. , 12. ],
        [ 7.4, 14.8, 22.2],
        [ 7. , 14. , 21. ]]])

In [183]:
a1.shape

(3,)

In [184]:
a2_reshape.shape

(2, 3, 1)

In [186]:
# transpose - switches the axis
# like - transpose matrix in maths
a2.T

array([[1. , 4. ],
       [2. , 7.4],
       [3.4, 7. ]])

In [188]:
a2_transpose = a2.T

In [189]:
a2_transpose.shape

(3, 2)

In [190]:
a3.shape

(2, 3, 3)

In [191]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 13],
        [14, 15, 16],
        [17, 18, 19]]])

In [192]:
a3_transpose = a3.T

In [194]:
a3_transpose

array([[[ 1, 10],
        [ 4, 14],
        [ 7, 17]],

       [[ 2, 11],
        [ 5, 15],
        [ 8, 18]],

       [[ 3, 13],
        [ 6, 16],
        [ 9, 19]]])

In [195]:
a3_transpose.shape

(3, 3, 2)

In [196]:
a3_transpose * a2_transpose

array([[[  1. ,  40. ],
        [  8. , 103.6],
        [ 23.8, 119. ]],

       [[  2. ,  44. ],
        [ 10. , 111. ],
        [ 27.2, 126. ]],

       [[  3. ,  52. ],
        [ 12. , 118.4],
        [ 30.6, 133. ]]])

# Dot Product

In [210]:
np.random.seed(0)
mat1 = np.random.randint(10,size=(5,3))
mat2 = np.random.randint(10,size=(5,3))
mat3 = np.random.randint(10,size=(3,5))

In [211]:
mat1,mat2

(array([[5, 0, 3],
        [3, 7, 9],
        [3, 5, 2],
        [4, 7, 6],
        [8, 8, 1]]),
 array([[6, 7, 7],
        [8, 1, 5],
        [9, 8, 9],
        [4, 3, 0],
        [3, 5, 0]]))

In [212]:
mat1

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [213]:
mat2

array([[6, 7, 7],
       [8, 1, 5],
       [9, 8, 9],
       [4, 3, 0],
       [3, 5, 0]])

In [214]:
mat1.shape

(5, 3)

In [215]:
mat2.shape

(5, 3)

In [216]:
mat1*mat2

array([[30,  0, 21],
       [24,  7, 45],
       [27, 40, 18],
       [16, 21,  0],
       [24, 40,  0]])

In [217]:
mat1-mat2

array([[-1, -7, -4],
       [-5,  6,  4],
       [-6, -3, -7],
       [ 0,  4,  6],
       [ 5,  3,  1]])

In [218]:
mat1+mat2

array([[11,  7, 10],
       [11,  8, 14],
       [12, 13, 11],
       [ 8, 10,  6],
       [11, 13,  1]])

In [219]:
# like - cross production of matrix in 12th maths
np.dot(mat1,mat3)

array([[ 37,  42,  40,  17,  36],
       [108, 111,  73,  39,  79],
       [ 39,  42,  59,  11,  28],
       [ 83,  87,  81,  28,  61],
       [ 49,  57, 120,  12,  39]])

In [220]:
np.dot(mat2,mat3)

array([[ 96, 102,  97,  34,  74],
       [ 64,  72,  71,  28,  60],
       [123, 132, 128,  45,  98],
       [ 17,  21,  53,   4,  15],
       [ 21,  24,  59,   3,  14]])

In [221]:
np.dot(mat3,mat1)

array([[ 71,  92,  58],
       [ 53,  64,  51],
       [144, 147, 139]])

In [222]:
np.dot(mat3,mat2)

array([[121,  99, 101],
       [108,  85,  99],
       [163, 119, 108]])

In [223]:
# rule - two matrix shape first A - shape - (a,b)
#                        second B - shape - (b,c)
#                         ans   C - shape - (a,c)
# here - dot(A,B) != dot(B,A)

In [224]:
# here transpose mat2 
trans_mat2 = mat2.T

In [225]:
trans_mat2.shape

(3, 5)

In [226]:
np.dot(mat1,trans_mat2)

array([[ 51,  55,  72,  20,  15],
       [130,  76, 164,  33,  44],
       [ 67,  39,  85,  27,  34],
       [115,  69, 146,  37,  47],
       [111,  77, 145,  56,  64]])

In [227]:
np.dot(trans_mat2,mat1)

array([[121, 153, 135],
       [114, 108,  69],
       [ 77,  80,  84]])

# Comparison Operators

In [228]:
a1

array([1, 2, 3])

In [229]:
a2

array([[1. , 2. , 3.4],
       [4. , 7.4, 7. ]])

In [230]:
a1>a2

array([[False, False, False],
       [False, False, False]])

In [231]:
a1>=a2

array([[ True,  True, False],
       [False, False, False]])

In [235]:
a2==a1

array([[ True,  True, False],
       [False, False, False]])

In [236]:
a1<a2

array([[False, False,  True],
       [ True,  True,  True]])

In [237]:
a1<=a2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [238]:
a2>2

array([[False, False,  True],
       [ True,  True,  True]])

In [239]:
a1<3

array([ True,  True, False])

In [240]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [241]:
a1 == a2

array([[ True,  True, False],
       [False, False, False]])

In [242]:
np.equal(a1,a1)

array([ True,  True,  True])

In [243]:
%timeit np.equal(a1,a1)

438 ns ± 17.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [244]:
%timeit a1==a1

411 ns ± 12.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [262]:
np.random.seed(0)
aa1 = np.random.randint(10,size=(1000000))

In [263]:
aa1

array([5, 0, 3, ..., 0, 8, 6])

In [264]:
np.random.seed(0)
aa2 = np.random.randint(10,size=(1000000))

In [265]:
aa2

array([5, 0, 3, ..., 0, 8, 6])

In [266]:
%timeit np.equal(aa1,aa1)

572 µs ± 10.9 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [267]:
%timeit aa1==aa1

619 µs ± 29.5 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [268]:
%timeit np.equal(aa1,aa2)

768 µs ± 58.3 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [269]:
%timeit aa1==aa2

829 µs ± 29 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Sorting Arrays

In [270]:
rondam_array

array([[4, 5, 6, 8, 5],
       [5, 8, 1, 0, 6],
       [0, 9, 5, 5, 6]])

In [272]:
rondam_array.shape

(3, 5)

In [276]:
np.sort(rondam_array) # raw wise sorting

array([[4, 5, 5, 6, 8],
       [0, 1, 5, 6, 8],
       [0, 5, 5, 6, 9]])

In [277]:
np.argsort(rondam_array)

array([[0, 1, 4, 2, 3],
       [3, 2, 0, 4, 1],
       [0, 2, 3, 4, 1]], dtype=int64)

In [278]:
np.argsort(a2)

array([[0, 1, 2],
       [0, 2, 1]], dtype=int64)

In [279]:
np.argmax(a1)

2

In [280]:
np.argmin(a2)

0

In [281]:
np.argmax(rondam_array,axis=0)

array([1, 2, 0, 0, 1], dtype=int64)

In [282]:
np.argmax(rondam_array,axis=1)

array([3, 1, 1], dtype=int64)

# Simple Dot product Examples

In [2]:
import numpy as np

In [3]:
weekly_butter_sales = np.random.randint(10,size=(5,3))

In [4]:
weekly_butter_sales

array([[2, 2, 8],
       [7, 5, 2],
       [8, 7, 4],
       [5, 5, 2],
       [0, 3, 4]])

In [5]:
import pandas as pd

In [11]:
#create data freame
df_weekly_butter_sales = pd.DataFrame(weekly_butter_sales, index = ["M","T","W","TH","F"], columns = ["SB","GB","SB"])

In [12]:
df_weekly_butter_sales

SB  GB  SB
M    2   2   8
T    7   5   2
W    8   7   4
TH   5   5   2
F    0   3   4

In [13]:
butter_sales_price = np.array([6,8,10])

In [14]:
butter_sales_price 

array([ 6,  8, 10])

In [22]:
butter_sales_price.shape

(3,)

In [18]:
t_butter_sales_price = butter_sales_price.T

In [21]:
t_butter_sales_price.shape

(3,)

In [19]:
t_butter_sales_price 

array([ 6,  8, 10])

In [25]:
df_butter_sales_price = pd.DataFrame(t_butter_sales_price.reshape(1,3),index = ["price"],columns = ["SB","GB","BB"])

In [26]:
df_butter_sales_price

SB  GB  BB
price   6   8  10

In [27]:
total_butter_price = np.dot(weekly_butter_sales,t_butter_sales_price.reshape(3,1))

In [28]:
total_butter_price

array([[108],
       [102],
       [144],
       [ 90],
       [ 64]])

In [29]:
df_total_butter_price = pd.DataFrame(total_butter_price,columns=["Total"])

In [30]:
df_total_butter_price

Total
0    108
1    102
2    144
3     90
4     64

In [31]:
df_weekly_butter_sales["Total"]=total_butter_price

In [32]:
df_weekly_butter_sales

SB  GB  SB  Total
M    2   2   8    108
T    7   5   2    102
W    8   7   4    144
TH   5   5   2     90
F    0   3   4     64

In [33]:
butter_sales_price 

array([ 6,  8, 10])

# Practical - Numpy in Action

<img src="numpy-images/panda.png">

In [39]:
#Turn an image into a numpy array
from matplotlib.image import imread
panda = imread("numpy-images/panda.png")

In [40]:
type(panda)

numpy.ndarray

In [41]:
print(type(panda))

<class 'numpy.ndarray'>


In [42]:
panda

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [43]:
panda.size

24465000

In [44]:
panda.shape

(2330, 3500, 3)

In [45]:
panda.ndim

3

In [46]:
panda[:5]

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.